### ISSUE TITLE
add sample outputs to your README

### ISSUE THREAD

**Issue by choucavalier** [XaeLee/CASTOR#15]
hey! saw your linkedin post looking for work. i think adding some sample outputs of your software and screenshots of the GUI (or a GIF animation based on a screen recording) would make this repo more attractive. most people won't download the code, compile and run the software themselves

**Comment by XaeLee** [comment]
Hi! Thanks for the feedback! Yeah, I added a small screenshot of the application's GUI on the Linkedin presentation of CASTOR in my profile, but the repo in itself could be prettier you're right!
I'll get to work on this soon

**Comment by XaeLee** [comment]
![castorBanner](https://github.com/user-attachments/assets/63caaca1-7d21-4315-bdcc-a5cea601e371)
![castorGUIAnimation](https://github.com/user-attachments/assets/a0e53c45-acd0-45fe-ba3b-3bcd4b2a0db0)

Illustrations for a better read me
